[pytest]
testpaths = tests
python_files = *.py
python_classes = *Test
python_functions = test_*
addopts = -m "not nki" --ignore=tests/end_to_end/test_triton_kernels.py

markers =
  nki: NKI-specific tests
