"""The TTIR goldens each Triton release reads, and the pins of each text.

The base goldens (``tests/golden/ir/ttir/`` and ``reader_ttir/``) were
printed by Triton 3.6, the base release; every release reads them. A later
release's own printing of a golden lives in ``ttir_<release>/`` /
``reader_ttir_<release>/`` (generated by ``generate_ttir.py`` /
``generate_reader_ttir.py`` under that release) and shadows the base copy
of the same name under that release. A text's pins are those of the
release that printed it: ``expected.json`` for the base goldens,
``expected_<release>.json`` for a release's own.

Only reads ``triton.__version__`` at import: importing this module never
fails on a release without a walk-layer table (the IR tests then skip,
D29, or fail closed under the override).

Not a test module: pytest imports it (python_files = *.py) and finds nothing.
"""

from __future__ import annotations

import json
from pathlib import Path

from tilelens.ir import _mlir_walk as W

REPO = Path(__file__).resolve().parents[3]
GOLDEN = REPO / "tests" / "golden" / "ir"
BASE_RELEASE = "3.6"  # the release that printed ttir/ and reader_ttir/
RELEASE = W.triton_release()[0]  # the installed Triton's

# Base goldens a release's parser rejects, because its printer spells a
# construct differently: name -> a fragment of the parser's diagnostic.
# Each is shadowed by that release's own printing (generate_ttir.py's
# RESPELLED), so the release keeps the coverage.
BASE_UNPARSABLE: dict[str, dict[str, str]] = {
    # `!tt.tensordesc<tensor<32x32xf16>>` is `!tt.tensordesc<32x32xf16>` on 3.8
    "3.8": {
        name: "tensor descriptors must not wrap tensor types"
        for name in (
            "adv_descs.ttir",
            "golden_matmul_tma_s1_sm90.ttir",
            "golden_matmul_tma_s3_sm90.ttir",
            "golden_matmul_tma_ws_s3_sm90.ttir",
        )
    },
}


def own_dir(kind: str, release: str) -> Path:
    """The directory of ``release``'s own goldens of ``kind`` ("ttir" or
    "reader_ttir"); the base release's are the base directory."""
    return GOLDEN / (kind if release == BASE_RELEASE else f"{kind}_{release}")


def releases_with_goldens(kind: str = "ttir") -> list[str]:
    """Every release with goldens of ``kind``, the base release first."""
    own = sorted(
        p.name[len(kind) + 1 :] for p in GOLDEN.glob(f"{kind}_*") if p.is_dir()
    )
    return [BASE_RELEASE, *own]


def texts(kind: str, release: str = RELEASE) -> dict[str, Path]:
    """name -> the golden ``release`` reads: its own printing where it has
    one, else the base golden."""
    got = {p.name: p for p in sorted(own_dir(kind, BASE_RELEASE).glob("*.ttir"))}
    if release != BASE_RELEASE:
        got.update({p.name: p for p in sorted(own_dir(kind, release).glob("*.ttir"))})
    return dict(sorted(got.items()))


def printed_by(path: Path) -> str:
    """The release that printed a golden."""
    for kind in ("reader_ttir", "ttir"):
        if path.parent.name.startswith(f"{kind}_"):
            return path.parent.name[len(kind) + 1 :]
    return BASE_RELEASE


def pins_path(release: str) -> Path:
    """The pins of the texts ``release`` printed (``ttir/`` goldens)."""
    return GOLDEN / (
        "expected.json" if release == BASE_RELEASE else f"expected_{release}.json"
    )


def pins(release: str) -> dict:
    path = pins_path(release)
    return json.loads(path.read_text(encoding="utf-8")) if path.exists() else {}
